### PR TITLE
Opacity feature for text watermarker

### PR DESCRIPTION
**Pull request by ismailocal**

### CODE REVIEW

**Comment by filippotoso** [comment]
Replace  

```php
127 * $opacity
```
with
```php
 255 * $opacity
```
and I'll approve the PR

**Comment by madurapa** [comment]
This PR was merged two years ago?

**Comment by filippotoso** [comment]
Sorry

**Comment by madurapa** [comment]
To clarify, this PR no longer exists. if someone refers to this in the future. Instead, we have to use the Alpha channel in the `color()` method.
`The color of the text in #RRGGBBAA (Red, Green, Blue, and Alpha). For instance #FF00007F (Red with 50% opacity)`

**Pull request merged**
